//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2018 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------------ Structures ------------------------

// already defined in /usr/include/x86_64-linux-gnu/bits/libio.h
#if 0
struct _IO_FILE {
    int32_t e0;
};
#endif

// --------------------- Global Variables ---------------------

int32_t g1 = 0;
int32_t g2 = 0;
int32_t g3 = 0;

// ------------------------ Functions -------------------------

// Address range: 0x804865c - 0x8048955
int main(int argc, char ** argv) {
    int32_t v1 = 0; // esp
    puts("\n#################### Welcome to Little Tommy's Handy yet Elegant and Advanced Program ####################");
    char * size; // bp-276
    int32_t v2 = (int32_t)&size; // 0x8048714
    int32_t v3; // bp-288
    int32_t v4 = (int32_t) &v3; // 0x8048693
    // branch -> 0x8048693
    while (true) {
        // 0x8048693
        *(int32_t *)(v4 - 16) = (int32_t)"\n1. Create account\n2. Display account\n3. Delete account\n4. Add memo\n5. Print flag\n\nPlease enter an operation number: ";
        int32_t * format;
        printf((char *)&format);
        int32_t c = getchar(); // 0x80486a3
        // branch -> 0x80486af
        int32_t c2; // 0x80486af
        while (true) {
          lab_0x80486af:
            // 0x80486af
            c2 = getchar();
            char v5 = c2; // 0x80486b4
            if (v5 != 10 != v5 != -1) {
                // break -> 0x80486cc
                break;
            }
            // continue -> 0x80486af
        }
        // 0x80486cc
        char * str3;
        switch (0x1000000 * c / 0x1000000) {
            default: {
                // 0x80486cc
                v4 = v1;
                // branch -> 0x8048693
                continue;
            }
            case 49: {
                // 0x80486e4
                *(int32_t *)(v1 - 16) = 72;
                g2 = (int32_t)malloc(0x1000000 * c2 / 0x1000000);
                *(int32_t *)v1 = (int32_t)"\nFirst name: ";
                printf((char *)&format);
                *(int32_t *)(v1 + 8) = g1;
                *(int32_t *)(v1 + 4) = 256;
                *(int32_t *)v1 = v2;
                char * str = (char *)(c2 % 256); // 0x804871b
                fgets(str, (int32_t)&format, (struct _IO_FILE *)&format);
                *(int32_t *)(v1 + 8) = 30;
                *(int32_t *)(v1 + 4) = v2;
                *(int32_t *)v1 = g2;
                strncpy(str, (char *)&format, (int32_t)&format);
                *(int32_t *)v1 = g2;
                int32_t len = strlen(str); // 0x8048748
                char * str2 = (char *)len; // 0x8048750
                int32_t v6 = g2; // 0x8048773
                if (len > 30) {
                    // 0x8048773
                    *(char *)(v6 + 31) = 0;
                    // branch -> 0x804877c
                } else {
                    // 0x804875f
                    *(char *)(v6 + len - 1) = 0;
                    // branch -> 0x804877c
                }
                // 0x804877c
                *(int32_t *)(v1 - 16) = (int32_t)"Last name: ";
                printf((char *)&format);
                *(int32_t *)(v1 + 8) = g1;
                *(int32_t *)(v1 + 4) = 256;
                *(int32_t *)v1 = v2;
                fgets(str2, (int32_t)size, (struct _IO_FILE *)&format);
                *(int32_t *)(v1 + 8) = 30;
                *(int32_t *)(v1 + 4) = v2;
                *(int32_t *)v1 = g2 + 32;
                strncpy(str2, size, (int32_t)&format);
                *(int32_t *)v1 = g2 + 32;
                int32_t len2 = strlen(str2); // 0x80487d2
                int32_t v7 = g2; // 0x80487fe
                if (len2 > 30) {
                    // 0x80487fe
                    *(char *)(v7 + 63) = 0;
                    // branch -> 0x8048807
                } else {
                    // 0x80487e9
                    *(char *)(len2 + 31 + v7) = 0;
                    // branch -> 0x8048807
                }
                // 0x8048807
                *(int32_t *)(v1 - 12) = g2;
                *(int32_t *)(v1 - 16) = (int32_t)"\nThank you, your account number %d.\n";
                printf((char *)&format);
                v4 = v1 + 16;
                str3 = (char *)len2;
                // branch -> 0x8048693
                continue;
            }
            case 50: {
                int32_t v8 = g2; // 0x8048822
                if (v8 != 0) {
                    // 0x8048840
                    *(int32_t *)(v1 - 16) = *(int32_t *)(v8 + 64);
                    *(int32_t *)(v1 - 20) = v8 + 32;
                    *(int32_t *)(v1 - 24) = v8;
                    *(int32_t *)(v1 - 28) = v8;
                    *(int32_t *)(v1 - 32) = (int32_t)"\n################ Account no. %d ################\nFirst name: %s\nLast name: %s\nAccount balance: %d\n\n";
                    printf((char *)&format);
                    v4 = v1 + 32;
                    // branch -> 0x8048693
                    continue;
                } else {
                    // 0x804882b
                    *(int32_t *)(v1 - 16) = (int32_t)"\nSorry, no account found.";
                    puts(str3);
                    v4 = v1 + 16;
                    // branch -> 0x8048693
                    continue;
                }
            }
            case 51: {
                int32_t v9 = g2; // 0x8048875
                if (v9 != 0) {
                    // 0x8048893
                    *(int32_t *)(v1 - 16) = v9;
                    free((int32_t *)str3);
                    *(int32_t *)v1 = (int32_t)"\nAccount deleted successfully";
                    puts(str3);
                    v4 = v1 + 16;
                    // branch -> 0x8048693
                    continue;
                } else {
                    // 0x804887e
                    *(int32_t *)(v1 - 16) = (int32_t)"\nSorry, no account found.";
                    puts(str3);
                    v4 = v1 + 16;
                    // branch -> 0x8048693
                    continue;
                }
            }
            case 52: {
                // 0x80488b9
                *(int32_t *)(v1 - 16) = (int32_t)"\nPlease enter memo:";
                puts(str3);
                *(int32_t *)(v1 + 8) = g1;
                *(int32_t *)(v1 + 4) = 256;
                *(int32_t *)v1 = v2;
                fgets(str3, (int32_t)size, (struct _IO_FILE *)&format);
                *(int32_t *)v1 = v2;
                int32_t v10 = (int32_t)strdup(str3); // 0x80488f0
                g3 = v10;
                *(int32_t *)(v1 + 4) = v10;
                *(int32_t *)v1 = (int32_t)"\nThank you, please keep this reference number number safe: %d.\n";
                printf((char *)&format);
                v4 = v1 + 16;
                // branch -> 0x8048693
                continue;
            }
            case 53: {
                int32_t v11 = g2; // 0x8048915
                if (v11 != 0) {
                    // 0x804891e
                    if (*(int32_t *)(v11 + 64) == 0x6b637566) {
                        // 0x804892d
                        *(int32_t *)(v1 - 16) = (int32_t)"/bin/cat flag";
                        system(str3);
                        // branch -> 0x804894f
                      lab_0x804894f:
                        // 0x804894f
                        v4 = v1 + 16;
                        // branch -> 0x8048693
                        continue;
                    }
                }
                // 0x804893f
                *(int32_t *)(v1 - 16) = (int32_t)"\nNope.";
                puts(str3);
                // branch -> 0x804894f
                goto lab_0x804894f;
            }
        }
    }
}

// --------------- Dynamically Linked Functions ---------------

// char * fgets(char * restrict s, int n, FILE * restrict stream);
// void free(void * ptr);
// int getchar(void);
// void * malloc(size_t size);
// int printf(const char * restrict format, ...);
// int puts(const char * s);
// char * strdup(const char * s);
// size_t strlen(const char * s);
// char * strncpy(char * restrict dest, const char * restrict src, size_t n);
// int system(const char * command);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (5.4.0)
// Detected functions: 1
// Decompilation date: 2018-08-22 22:38:07
